# Generated by Django 4.2 on 2026-04-05 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите полное официальное название издания без сокращений.', max_length=500, verbose_name='Название журнала')),
                ('issn_print', models.CharField(blank=True, help_text='Международный стандартный номер печатного издания в формате XXXX-XXXX.', max_length=9, null=True, verbose_name='ISSN (print)')),
                ('issn_online', models.CharField(blank=True, help_text='Международный стандартный номер электронной версии издания в формате XXXX-XXXX.', max_length=9, null=True, verbose_name='ISSN (online)')),
                ('publisher', models.CharField(blank=True, help_text='Например: Elsevier, Springer, Наука, МГУ.', max_length=255, verbose_name='Издательство')),
                ('is_scopus', models.BooleanField(default=False, help_text='Отметьте, если журнал индексируется в базе данных Scopus на текущий момент.', verbose_name='Scopus')),
                ('is_wos', models.BooleanField(default=False, help_text='Отметьте, если журнал входит в Core Collection Web of Science.', verbose_name='Web of Science')),
                ('is_vak', models.BooleanField(default=False, help_text='Входит ли журнал в перечень рецензируемых научных изданий, рекомендованных Минобрнауки РФ.', verbose_name='ВАК')),
                ('is_rinz', models.BooleanField(default=False, help_text='Входит ли издание в Российский индекс научного цитирования (eLibrary.ru).', verbose_name='РИНЦ')),
                ('is_white_list', models.BooleanField(default=False, help_text='Входит ли журнал в Национальный белый список (РЦНИ).', verbose_name='Белый список')),
                ('quartile', models.CharField(choices=[('Q1', 'Q1 (Высший)'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('n/a', 'Нет квартиля')], default='n/a', help_text='Категория научного журнала от Q1 (самый высокий рейтинг) до Q4 (самый низкий).', max_length=3, verbose_name='Квартиль')),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=3, help_text='Показатель цитируемости журнала (Journal Impact Factor). Используйте точку как разделитель.', max_digits=6, null=True, verbose_name='Импакт-фактор')),
                ('website', models.URLField(blank=True, help_text='Ссылка на главную страницу журнала или страницу издателя.', max_length=500, verbose_name='Сайт журнала')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите полное название статьи на языке оригинала.', max_length=1000, verbose_name='Название статьи')),
                ('external_authors', models.CharField(blank=True, help_text='Если есть соавторы не из нашего вуза, перечислите их через запятую (Фамилия И.О.).', max_length=500, verbose_name='Внешние соавторы')),
                ('doi', models.CharField(blank=True, help_text='Цифровой идентификатор объекта (например: 10.1000/xyz123). Уникален для каждой статьи.', max_length=100, null=True, unique=True, verbose_name='DOI')),
                ('year', models.PositiveIntegerField(help_text='Например: 2024.', verbose_name='Год публикации')),
                ('volume', models.CharField(blank=True, help_text='Volume (номер тома журнала).', max_length=50, verbose_name='Том')),
                ('issue', models.CharField(blank=True, help_text='Issue/Number (номер выпуска журнала).', max_length=50, verbose_name='Номер')),
                ('pages', models.CharField(blank=True, help_text='Диапазон страниц (например: 120-135).', max_length=50, verbose_name='Страницы')),
                ('article_type', models.CharField(choices=[('original', 'Оригинальная статья'), ('review', 'Обзорная статья'), ('editorial', 'Редакционная статья'), ('conference', 'Материалы конференции'), ('short_comm', 'Краткое сообщение')], default='original', max_length=20, verbose_name='Тип публикации')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('accepted', 'Принято в печать'), ('submitted', 'На рассмотрении')], default='published', max_length=20, verbose_name='Статус публикации')),
                ('url', models.URLField(blank=True, help_text='Прямая ссылка на страницу статьи на сайте издательства.', verbose_name='Ссылка на статью')),
                ('abstract', models.TextField(blank=True, help_text='Краткое содержание статьи (полезно для поиска).', verbose_name='Аннотация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в систему')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('authors', models.ManyToManyField(help_text='Выберите одного или нескольких преподавателей из системы, являющихся авторами.', related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Авторы (преподаватели)')),
                ('journal', models.ForeignKey(help_text='Выберите журнал, в котором опубликована статья. Если журнала нет в списке, его нужно добавить.', on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='main_app.journal', verbose_name='Журнал')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-year', 'title'],
            },
        ),
    ]
