# Generated by Django 4.2 on 2026-04-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Журнал Белого списка', 'verbose_name_plural': 'Журналы Белого списка'},
        ),
        migrations.RemoveField(
            model_name='journal',
            name='impact_factor',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='is_rinz',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='is_scopus',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='is_vak',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='is_white_list',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='is_wos',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='issn_online',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='issn_print',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='quartile',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='website',
        ),
        migrations.AddField(
            model_name='journal',
            name='agriculture_agricola',
            field=models.BooleanField(blank=True, default=None, help_text='База данных Национальной сельскохозяйственной библиотеки США', null=True, verbose_name='Agriculture (Agricola)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='agriculture_cab',
            field=models.BooleanField(blank=True, default=None, help_text='Прикладные науки о жизни и сельское хозяйство', null=True, verbose_name='Agriculture (CAB Abstracts)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='biology_abstracts',
            field=models.BooleanField(blank=True, default=None, help_text='Аннотации по биологическим наукам', null=True, verbose_name='Biology Abstracts'),
        ),
        migrations.AddField(
            model_name='journal',
            name='biomedicine_embase',
            field=models.BooleanField(blank=True, default=None, help_text='База данных по биомедицине и фармакологии', null=True, verbose_name='Biomedicine (Embase)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='chemical_ref_index',
            field=models.BooleanField(blank=True, default=None, help_text='Химический справочный индекс', null=True, verbose_name='Chemical Ref. Index'),
        ),
        migrations.AddField(
            model_name='journal',
            name='chemistry_index',
            field=models.BooleanField(blank=True, default=None, help_text='Специализированный индекс химических изданий', null=True, verbose_name='Chemistry Index'),
        ),
        migrations.AddField(
            model_name='journal',
            name='comp_science_dblp',
            field=models.BooleanField(blank=True, default=None, help_text='Библиография по компьютерным наукам', null=True, verbose_name='Comp. Science (DBLP)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='date_accepted',
            field=models.DateField(blank=True, default=None, help_text='Дата включения журнала в Белый список', null=True, verbose_name='Дата принятия'),
        ),
        migrations.AddField(
            model_name='journal',
            name='date_discontinued',
            field=models.DateField(blank=True, default=None, help_text='Дата, после которой журнал перестал входить в Белый список', null=True, verbose_name='Дата исключения'),
        ),
        migrations.AddField(
            model_name='journal',
            name='doaj_id',
            field=models.CharField(blank=True, default=None, help_text='Идентификатор журнала в базе DOAJ', max_length=100, null=True, verbose_name='DOAJ ID'),
        ),
        migrations.AddField(
            model_name='journal',
            name='engineering_compendex',
            field=models.BooleanField(blank=True, default=None, help_text='Наиболее полная база инженерных публикаций', null=True, verbose_name='Engineering (Compendex)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='food_science_fsta',
            field=models.BooleanField(blank=True, default=None, help_text='База данных по пищевым наукам и технологиям', null=True, verbose_name='Food Science (FSTA)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='geography_geobase',
            field=models.BooleanField(blank=True, default=None, help_text='Междисциплинарная база данных о Земле', null=True, verbose_name='Geography (Geobase)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='geology_georef',
            field=models.BooleanField(blank=True, default=None, help_text='База данных Американского геологического института', null=True, verbose_name='Geology (GeoRef)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='health_safety_abs',
            field=models.BooleanField(blank=True, default=None, help_text='Абстракты по гигиене и безопасности труда', null=True, verbose_name='Health & Safety Abs.'),
        ),
        migrations.AddField(
            model_name='journal',
            name='humanities_erih_plus',
            field=models.BooleanField(blank=True, default=None, help_text='Европейский индекс для гуманитарных и социальных наук', null=True, verbose_name='Humanities (ERIH PLUS)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='issns',
            field=models.CharField(blank=True, default=None, help_text='Международные стандартные серийные номера (p-ISSN, e-ISSN)', max_length=100, null=True, verbose_name='ISSN(s)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='level_2023',
            field=models.IntegerField(blank=True, default=None, help_text='Категория журнала в Белом списке на 2023 год (1-4)', null=True, verbose_name='Уровень 2023'),
        ),
        migrations.AddField(
            model_name='journal',
            name='level_2025',
            field=models.IntegerField(blank=True, default=None, help_text='Прогнозная или утвержденная категория на 2025 год', null=True, verbose_name='Уровень 2025'),
        ),
        migrations.AddField(
            model_name='journal',
            name='medicine_medline',
            field=models.BooleanField(blank=True, default=None, help_text='Крупнейшая база данных по медицине и биологии', null=True, verbose_name='Medicine (Medline)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='open_access_doaj',
            field=models.BooleanField(blank=True, default=None, help_text='Журнал открытого доступа, индексируемый в DOAJ', null=True, verbose_name='Open Access (DOAJ)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='petroleum_index',
            field=models.BooleanField(blank=True, default=None, help_text='Индекс публикаций в нефтегазовой сфере', null=True, verbose_name='Petroleum Index'),
        ),
        migrations.AddField(
            model_name='journal',
            name='physics_inspec',
            field=models.BooleanField(blank=True, default=None, help_text='База данных по физике и компьютерным наукам', null=True, verbose_name='Physics (Inspec)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='poultry_science_wpsa',
            field=models.BooleanField(blank=True, default=None, help_text='База публикаций по птицеводству', null=True, verbose_name='Poultry Science (WPSA)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='rsci',
            field=models.BooleanField(blank=True, default=None, help_text='Входит ли журнал в Russian Science Citation Index', null=True, verbose_name='RSCI (РИНЦ)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='scopus',
            field=models.BooleanField(blank=True, default=None, help_text='Индексируется ли журнал в базе Scopus', null=True, verbose_name='Scopus'),
        ),
        migrations.AddField(
            model_name='journal',
            name='sociology_socabs',
            field=models.BooleanField(blank=True, default=None, help_text='База данных по социологии и социальным наукам', null=True, verbose_name='Sociology (SocAbs)'),
        ),
        migrations.AddField(
            model_name='journal',
            name='srcid',
            field=models.CharField(blank=True, default=None, help_text='Уникальный идентификатор журнала в системе Scopus', max_length=50, null=True, verbose_name='Scopus SourceID'),
        ),
        migrations.AddField(
            model_name='journal',
            name='wos_cc',
            field=models.BooleanField(blank=True, default=None, help_text='Входит ли журнал в Core Collection Web of Science', null=True, verbose_name='Web of Science CC'),
        ),
        migrations.AddField(
            model_name='journal',
            name='zoology_record',
            field=models.BooleanField(blank=True, default=None, help_text='База данных по биологии животных и зоологии', null=True, verbose_name='Zoology Record'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.TextField(blank=True, default=None, help_text='Полное официальное название научного издания', null=True, verbose_name='Название журнала'),
        ),
    ]
