# Generated by Django 4.2 on 2026-04-15 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_article_options_alter_journal_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='level_2025',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='level_2023',
        ),
    ]
