# Generated by Django 4.2 on 2026-04-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_level_2025_journal_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='state',
            field=models.BooleanField(blank=True, default=None, help_text='Входит ли в белый список', null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='level',
            field=models.IntegerField(blank=True, default=None, help_text='утвержденная категория (q1 q2 q3 q4)', null=True, verbose_name='Уровень 2025'),
        ),
    ]
