# Generated by Django 4.2 on 2026-04-15 22:08

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('researcher_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Web of Science ResearcherID')),
                ('scopus_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Scopus Author ID')),
                ('orcid', models.CharField(blank=True, max_length=20, null=True, verbose_name='ORCID')),
                ('google_scholar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Google Scholar ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, help_text='Полное официальное название научного издания', null=True, verbose_name='Название журнала')),
                ('issns', models.CharField(blank=True, default=None, help_text='Международные стандартные серийные номера (p-ISSN, e-ISSN)', max_length=100, null=True, verbose_name='ISSN(s)')),
                ('state', models.BooleanField(blank=True, default=None, help_text='Входит ли в белый список', null=True)),
                ('level', models.IntegerField(blank=True, default=None, help_text='утвержденная категория (q1 q2 q3 q4)', null=True, verbose_name='Уровень 2025')),
                ('wos_cc', models.BooleanField(blank=True, default=None, help_text='Входит ли журнал в Core Collection Web of Science', null=True, verbose_name='Web of Science CC')),
                ('scopus', models.BooleanField(blank=True, default=None, help_text='Индексируется ли журнал в базе Scopus', null=True, verbose_name='Scopus')),
                ('srcid', models.CharField(blank=True, default=None, help_text='Уникальный идентификатор журнала в системе Scopus', max_length=50, null=True, verbose_name='Scopus SourceID')),
                ('rsci', models.BooleanField(blank=True, default=None, help_text='Входит ли журнал в Russian Science Citation Index', null=True, verbose_name='RSCI (РИНЦ)')),
                ('open_access_doaj', models.BooleanField(blank=True, default=None, help_text='Журнал открытого доступа, индексируемый в DOAJ', null=True, verbose_name='Open Access (DOAJ)')),
                ('doaj_id', models.CharField(blank=True, default=None, help_text='Идентификатор журнала в базе DOAJ', max_length=100, null=True, verbose_name='DOAJ ID')),
                ('humanities_erih_plus', models.BooleanField(blank=True, default=None, help_text='Европейский индекс для гуманитарных и социальных наук', null=True, verbose_name='Humanities (ERIH PLUS)')),
                ('physics_inspec', models.BooleanField(blank=True, default=None, help_text='База данных по физике и компьютерным наукам', null=True, verbose_name='Physics (Inspec)')),
                ('comp_science_dblp', models.BooleanField(blank=True, default=None, help_text='Библиография по компьютерным наукам', null=True, verbose_name='Comp. Science (DBLP)')),
                ('medicine_medline', models.BooleanField(blank=True, default=None, help_text='Крупнейшая база данных по медицине и биологии', null=True, verbose_name='Medicine (Medline)')),
                ('biomedicine_embase', models.BooleanField(blank=True, default=None, help_text='База данных по биомедицине и фармакологии', null=True, verbose_name='Biomedicine (Embase)')),
                ('agriculture_agricola', models.BooleanField(blank=True, default=None, help_text='База данных Национальной сельскохозяйственной библиотеки США', null=True, verbose_name='Agriculture (Agricola)')),
                ('agriculture_cab', models.BooleanField(blank=True, default=None, help_text='Прикладные науки о жизни и сельское хозяйство', null=True, verbose_name='Agriculture (CAB Abstracts)')),
                ('engineering_compendex', models.BooleanField(blank=True, default=None, help_text='Наиболее полная база инженерных публикаций', null=True, verbose_name='Engineering (Compendex)')),
                ('geology_georef', models.BooleanField(blank=True, default=None, help_text='База данных Американского геологического института', null=True, verbose_name='Geology (GeoRef)')),
                ('geography_geobase', models.BooleanField(blank=True, default=None, help_text='Междисциплинарная база данных о Земле', null=True, verbose_name='Geography (Geobase)')),
                ('chemical_ref_index', models.BooleanField(blank=True, default=None, help_text='Химический справочный индекс', null=True, verbose_name='Chemical Ref. Index')),
                ('food_science_fsta', models.BooleanField(blank=True, default=None, help_text='База данных по пищевым наукам и технологиям', null=True, verbose_name='Food Science (FSTA)')),
                ('health_safety_abs', models.BooleanField(blank=True, default=None, help_text='Абстракты по гигиене и безопасности труда', null=True, verbose_name='Health & Safety Abs.')),
                ('poultry_science_wpsa', models.BooleanField(blank=True, default=None, help_text='База публикаций по птицеводству', null=True, verbose_name='Poultry Science (WPSA)')),
                ('sociology_socabs', models.BooleanField(blank=True, default=None, help_text='База данных по социологии и социальным наукам', null=True, verbose_name='Sociology (SocAbs)')),
                ('chemistry_index', models.BooleanField(blank=True, default=None, help_text='Специализированный индекс химических изданий', null=True, verbose_name='Chemistry Index')),
                ('zoology_record', models.BooleanField(blank=True, default=None, help_text='База данных по биологии животных и зоологии', null=True, verbose_name='Zoology Record')),
                ('biology_abstracts', models.BooleanField(blank=True, default=None, help_text='Аннотации по биологическим наукам', null=True, verbose_name='Biology Abstracts')),
                ('petroleum_index', models.BooleanField(blank=True, default=None, help_text='Индекс публикаций в нефтегазовой сфере', null=True, verbose_name='Petroleum Index')),
                ('date_accepted', models.DateField(blank=True, default=None, help_text='Дата включения журнала в Белый список', null=True, verbose_name='Дата принятия')),
                ('date_discontinued', models.DateField(blank=True, default=None, help_text='Дата, после которой журнал перестал входить в Белый список', null=True, verbose_name='Дата исключения')),
            ],
            options={
                'verbose_name': 'Журнал Белого списка',
                'verbose_name_plural': 'Журналы Белого списка',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no name', max_length=120)),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
