# Generated by Django 4.2 on 2026-04-21 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название базы')),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
        migrations.AddField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='DOI'),
        ),
        migrations.AddField(
            model_name='article',
            name='full_biblio_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Полное библиографическое описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='main_app.journal', verbose_name='Журнал'),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_year',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Год публикации'),
        ),
        migrations.AddField(
            model_name='article',
            name='scientific_field',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Научное направление'),
        ),
        migrations.AddField(
            model_name='article',
            name='total_authors_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Общее количество авторов'),
        ),
        migrations.AddField(
            model_name='article',
            name='with_foreign_authors',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='С участием иностранных авторов'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Заголовок статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='citation_databases',
            field=models.ManyToManyField(blank=True, related_name='articles', to='main_app.citationdatabase', verbose_name='Базы цитирования'),
        ),
    ]
